export interface GalleryImage {
  src: string;
  width: number;
  height: number;
  alt: string;
  title: string;
  description: string;
  location: string;
  date: string;
  aiHint: string;
}

export const galleryData: GalleryImage[] = [
  // Neu: Porträts aus der SchächnerCloud
  {
    src: '/portraets/hochzeit-2115.jpeg',
    width: 1200,
    height: 1576,
    alt: 'Porträtfoto von Benedikt Schächner',
    title: 'Porträt – Hochzeit',
    description: 'Porträt aus einem Fotoshooting.',
    location: 'Fotostudio',
    date: '2025-06-25',
    aiHint: 'portrait man formal',
  },
  {
    src: '/portraets/hochzeit-21152.jpeg',
    width: 1200,
    height: 967,
    alt: 'Porträtfoto von Benedikt Schächner im Anzug',
    title: 'Porträt – Hochzeit II',
    description: 'Porträt aus einem Fotoshooting.',
    location: 'Fotostudio',
    date: '2025-06-25',
    aiHint: 'portrait man suit',
  },
  {
    src: '/portraets/portrait-2026-08-04-1.png',
    width: 1093,
    height: 1438,
    alt: 'Porträtfoto von Benedikt Schächner',
    title: 'Porträt 2026',
    description: 'Aktuelles Porträtfoto.',
    location: 'Fotostudio',
    date: '2026-08-04',
    aiHint: 'portrait man',
  },
  {
    src: '/portraets/portrait-2026-08-04-2.png',
    width: 1092,
    height: 1440,
    alt: 'Porträtfoto von Benedikt Schächner',
    title: 'Porträt 2026 II',
    description: 'Aktuelles Porträtfoto.',
    location: 'Fotostudio',
    date: '2026-08-04',
    aiHint: 'portrait man',
  },
  {
    src: '/portraets/img-1677.jpeg',
    width: 1000,
    height: 750,
    alt: 'Benedikt Schächner',
    title: 'Porträt',
    description: 'Porträt aus einem Fotoshooting.',
    location: 'Fotostudio',
    date: '2026-05-22',
    aiHint: 'person portrait',
  },
  {
    src: '/portraets/foto-55426293736.jpeg',
    width: 1200,
    height: 800,
    alt: 'Benedikt Schächner bei einer Veranstaltung',
    title: 'Veranstaltung',
    description: 'Foto von einer Veranstaltung.',
    location: 'Deutschland',
    date: '2026-07-29',
    aiHint: 'person event',
  },
  {
    src: '/portraets/img-5907.jpg',
    width: 750,
    height: 1248,
    alt: 'Porträtfoto von Benedikt Schächner',
    title: 'Porträt',
    description: 'Porträtfoto.',
    location: 'Fotostudio',
    date: '2026-03-16',
    aiHint: 'portrait man',
  },
  {
    src: '/portraets/img-7331.jpg',
    width: 1394,
    height: 2683,
    alt: 'Porträtfoto von Benedikt Schächner',
    title: 'Porträt',
    description: 'Porträtfoto.',
    location: 'Fotostudio',
    date: '2026-03-16',
    aiHint: 'portrait man',
  },
  {
    src: '/portraets/judo-1.jpg',
    width: 1372,
    height: 1000,
    alt: 'Benedikt Schächner beim Judo',
    title: 'Judo',
    description: 'Foto beim Judo.',
    location: 'Töging',
    date: '2026-03-02',
    aiHint: 'judo sport',
  },

  // crossmedia-3 ganz oben
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/crossmedia-3.jpeg',
    width: 600,
    height: 800,
    alt: 'Bayerische Rundfung',
    title: 'BR München',
    description: 'Preisverleihung Crossmedia 2025 im Bayerischen Rundfunk',
    location: 'München, Deutschland',
    date: '2024-11-20',
    aiHint: 'portrait person',
  },

  // restliche Bilder in beliebiger Reihenfolge
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/crossmedia-1.jpeg',
    width: 600,
    height: 800,
    alt: 'Interview',
    title: 'Crossmedia-Preisverleihung',
    description: 'Preisverleihung Crossmedia 2025 im Bayerischen Rundfunk',
    location: 'München, Deutschland',
    date: '2024-11-20',
    aiHint: 'portrait person',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/crossmedia-2.jpeg',
    width: 600,
    height: 800,
    alt: 'Urkunde',
    title: 'Preisträger mit "Notio"',
    description: 'Preisverleihung Crossmedia 2025 im Bayerischen Rundfunk',
    location: 'München, Deutschland',
    date: '2024-11-20',
    aiHint: 'portrait person',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/IMG_7331.jpg',
    width: 600,
    height: 800,
    alt: 'Porträtfoto',
    title: 'Benedikt',
    description: 'Nextcloud Community Conference 2025',
    location: 'Berlin, Deutschland',
    date: '2024-09-15',
    aiHint: 'portrait person',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/IMG_1677.JPG',
    width: 600,
    height: 800,
    alt: 'Heinz Nixdorf Museum',
    title: 'Heinz Nixdorf MuseumsForum',
    description: 'Die Young-Leaders-Academy 2023 im Heinz Nixdorf MuseumsForum.',
    location: 'Paderborn, Deutschland',
    date: '2024-09-14',
    aiHint: 'person presentation',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/IMG_8516.JPG',
    width: 800,
    height: 600,
    alt: 'Benedikt Schächner mit verschiedene Beleuchtungs-Techniken.',
    title: 'Lichtspiel',
    description: 'Crossmedia-Preisverleihung',
    location: 'München, Deutschland',
    date: '2024-06-20',
    aiHint: 'person casual',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/IMG_8836.JPG',
    width: 600,
    height: 800,
    alt: 'Benedikt Schächner im Anzug',
    title: 'Moderation',
    description:
      'Bei der Crossmedia-Preisverleihung des BR durften wir selbst als Moderatoren den Greenscreen ausprobieren.',
    location: 'München, Deutschland',
    date: '2024-11-23',
    aiHint: 'person formal',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner%20Download%20(1).jpeg',
    width: 600,
    height: 800,
    alt: 'Weiteres Porträtfoto',
    title: 'Porträt II',
    description: 'Porträt aus einem Fotoshooting in Töging.',
    location: 'Fotostudio, Töging',
    date: '2023-10-01',
    aiHint: 'portrait man',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner%20Download%20(2).jpeg',
    width: 600,
    height: 800,
    alt: 'Benedikt Schächner im Freien',
    title: 'Outdoor',
    description: 'Beim Spaziergang in der Nähe von Pleiskirchen.',
    location: 'In der Nähe von Pleiskirchen',
    date: '2024-07-10',
    aiHint: 'person outdoor',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner%20Download%20(3).jpeg',
    width: 600,
    height: 800,
    alt: 'Porträtfoto von Benedikt Schächner',
    title: 'Nahaufnahme',
    description: 'Nahaufnahme aus dem Studio.',
    location: 'Fotostudio, München',
    date: '2024-05-15',
    aiHint: 'person closeup',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner%20Download%20(4).jpeg',
    width: 800,
    height: 600,
    alt: 'Benedikt Schächner bei einer Veranstaltung',
    title: 'Networking',
    description: 'Im Gespräch bei der Young Leaders Akademie.',
    location: 'Young Leaders Akademie',
    date: '2023-11-18',
    aiHint: 'person event',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner%20Download.jpeg',
    width: 600,
    height: 800,
    alt: 'Profilbild von Benedikt Schächner',
    title: 'Profil',
    description: 'Profilfoto für berufliche Netzwerke.',
    location: 'Fotostudio, Töging',
    date: '2023-10-01',
    aiHint: 'person profile',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner%20Suche.jpeg',
    width: 800,
    height: 600,
    alt: 'Benedikt Schächner bei der Arbeit',
    title: 'Fokussiert',
    description:
      'Bei der Arbeit an einem neuen Web-Projekt im Home Office.',
    location: 'Home Office',
    date: '2024-08-05',
    aiHint: 'person working',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Benedikt%20Scha%CC%88chner.jpeg',
    width: 600,
    height: 800,
    alt: 'Ein weiteres Foto von Benedikt Schächner',
    title: 'Klassisch',
    description:
      'Schwarz-Weiß-Foto aus dem Studio.',
    location: 'Fotostudio, München',
    date: '2024-05-15',
    aiHint: 'person classic',
  },
  {
    src: 'https://raw.githubusercontent.com/SchBenedikt/portfolio/master/src/app/photos/benedikt/Download%20(1).jpeg',
    width: 800,
    height: 600,
    alt: 'Benedikt Schächner in Aktion',
    title: 'Aktion',
    description:
      'Während einer Medienscouts-Workshop-Session am KKG.',
    location: 'König-Karlmann-Gymnasium',
    date: '2024-03-22',
    aiHint: 'person action',
  },
];
