import { Globe2, Radio, ShieldCheck, Terminal, Check, ArrowUpRight, Wifi, Lock, Eye, Smartphone, Server, Leaf, Zap, Database } from 'lucide-react';

/** Small editorial illustrations, deliberately schematic rather than live product data. */
export default function ProjectArtwork({ slug }: { slug: string }) {
  return <div className={`project-visual visual-${slug}`} aria-hidden="true">
    <div className="visual-grain"/>
    {slug === 'notio' ? <div className="notio-preview"><div className="preview-top"><b>notio</b><span>Mein Überblick</span><i/></div><div className="preview-body"><div className="preview-nav"><span>Übersicht</span><span>Fächer</span><span>Aufgaben</span></div><div className="preview-main"><small>ALLES IM BLICK</small><strong>Raum fürs Lernen.</strong><div className="preview-chart">{[38,65,48,80,60,94,75].map((h,i) => <i key={i} style={{height:`${h}%`}}/>)}</div><div className="preview-task"><Check size={12}/> Gedanken ordnen. Weiterkommen.</div></div></div></div>
    : slug === 'meum-diarium' ? <div className="diarium-volume"><span className="book-spine"/><small>GESCHICHTE IN DER ICH-PERSPEKTIVE</small><strong>Meum<br/><em>Diarium.</em></strong><span className="book-rule"/><span>Caesar · Cicero · Seneca</span><span className="book-mark">MD</span></div>
    : slug === 'p-seminar' ? <div className="latin-magazine"><div className="magazine-back"/><div className="magazine-front"><small>P-SEMINAR · LATEIN · 2026</small><strong>Antike.<br/><em>Neu erzählt.</em></strong><div className="magazine-columns"><i/><i/><i/></div><span>Eine Zeitschrift aus dem Unterricht <ArrowUpRight size={15}/></span></div></div>
    : slug === 'technik-blog' ? <div className="server-preview"><div className="server-heading"><Terminal size={16}/><span>TECHNIK / WISSEN TEILEN</span></div><strong>Selbst hosten.<br/>Selbst verstehen.</strong><div className="server-stack">{['Linux', 'Docker', 'Nextcloud'].map((s,i) => <div key={s}><span>0{i+1}</span>{s}<i/></div>)}</div></div>
    : slug === 'wissenschaftswoche-2026' ? <div className="research-visual"><div className="research数据中心"><div className="dc-header"><Server size={14}/><span>DATACENTER MOND</span></div><div className="dc-grid"><div className="dc-server"><div className="dc-lights"><span/><span/><span/></div><div className="dc-slots">{[1,2,3,4].map(i => <div key={i}/>)}</div></div><div className="dc-server"><div className="dc-lights"><span/><span/><span/></div><div className="dc-slots">{[1,2,3,4].map(i => <div key={i}/>)}</div></div></div><div className="dc-stats"><div><Leaf size={10}/><span>92% effizient</span></div><div><Zap size={10}/><span>Solar powered</span></div></div></div><div className="research-globe-2"><Globe2 size={90} strokeWidth={.5}/><div className="research-ring"/><div className="research-ring research-ring-2"/></div><div className="research-moon"><span>Mond</span></div><div className="research-label-2"><span>ERDE ↔ WELTRAUM</span><strong>Nachhaltigkeit.<br/>Weitergedacht.</strong></div></div>
    : slug === 'tus-toeging-judo-instagram' ? <div className="judo-poster"><small>TUS TÖGING / JUDO</small><strong>柔道</strong><div className="judo-belt"/><span>Sport. Gemeinschaft. Geschichten.</span></div>
    : <div className="scouts-visual"><div className="scouts-grid"><div className="scouts-icon scouts-shield"><ShieldCheck size={42} strokeWidth={1}/></div><div className="scouts-icon scouts-wifi"><Wifi size={28} strokeWidth={1}/></div><div className="scouts-icon scouts-lock"><Lock size={24} strokeWidth={1}/></div><div className="scouts-icon scouts-eye"><Eye size={26} strokeWidth={1}/></div><div className="scouts-icon scouts-phone"><Smartphone size={30} strokeWidth={1}/></div><div className="scouts-icon scouts-radio"><Radio size={22} strokeWidth={1}/></div></div></div>}
  </div>;
}
